import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import AuthContext from "@/context/auth-context";
import OverlayProvider from "@/components/overlays/overlay-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Messenger Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthContext>
          {children}
          <OverlayProvider />
        </AuthContext>
      </body>
      <Toaster position="top-center" />
    </html>
  );
}
